export const hotelTypes = [
    "Budget",
    "Boutique",
    "Luxury",
    "Ski Resort",
    "Business",
    "Family",
    "Romantic",
    "Hiking Resort",
    "Cabin",
    "Beach Resort",
    "Golf Resort",
    "Motel",
    "All Inclusive",
    "Pet Friendly",
    "Self Catering",
]

export const hotelFacilities = [
    "Free Wi-Fi",
    "Free Parking",
    "Airport Shuttle",
    "Non-smoking Rooms",
    "Restaurant",
    "Room Service",
    "Fitness Center",
    "Bar",
    "Breakfast",
    "Swimming Pool",
    "Spa",
    "Pet Friendly",
    "Family Rooms",
    "Facilities for Disabled Guests",
    "Tea/Coffee Maker Free",
    "Private Bathroom",
    "Flat-Screen TV",
    "Terrace",
    "Ski Storage",
    "Ski Equipment",
    "Ski Pass Vendor",
]